  version: '3.8'

  services:
    mysql_business_app:
      image: mysql:8.1.0
      restart: 'no'
      environment:
        MYSQL_DATABASE: '${BA_MYSQL_DATABASE}'
        MYSQL_USER: '${BA_MYSQL_USER}'
        MYSQL_PASSWORD: '${BA_MYSQL_PASSWORD}'
        MYSQL_ROOT_PASSWORD: '${BA_MYSQL_ROOT_PASSWORD}'
      ports:
        - '${BA_DB_PORT}:3306'
      volumes:
        - ./mysql/data:/var/lib/mysql

