  version: '3.8'

  services:
    mysql_business_app:
      image: mysql:8.1.0
      restart: no
      environment:
        MYSQL_DATABASE: '${MYSQL_DATABASE}'
        MYSQL_USER: '${MYSQL_USER}'
        MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      ports:
        - '${DB_PORT}:3306'
      volumes:
        - ./mysql/data:/var/lib/mysql
   
